// Timberwolves GIFs shown on the pick reveal. Hosted by GIPHY (media.giphy.com);
// ids harvested from giphy.com searches 2026-09-16, kept to ~4.5 MB or less.
// Everyone sees the same GIF for a given pick number so the room laughs together.
window.WOLVES_GIFS = [
  { id: "2dIOuEvQksCJWuxA0i", who: "Timberwolves" },  // nba-playoffs-minnesota-timberwolves (0.1 MB)
  { id: "3mqIDhMQ1BSgUWMApx", who: "Timberwolves" },  // timberwolves-wolves-minnesota-timberwolves-wolvesback (0.2 MB)
  { id: "VmTpXJUQYX7TN68Ce4", who: "Anthony Edwards" },  // nba-ant-edwards-anthony (0.6 MB)
  { id: "cs9g1Sbn8ZFJdNV6vT", who: "Anthony Edwards" },  // nba-anthony-edwards (0.8 MB)
  { id: "3y85u3pMFOmD36UeQr", who: "Julius Randle" },  // nba-minnesota-timberwolves-julius-randle (0.8 MB)
  { id: "KcaoqoCTMzAA94fQb4", who: "Jaden McDaniels" },  // timberwolves-nba-minnesota-jadenmcdaniels (1.0 MB)
  { id: "8OrrfCG4SxGh2hKq14", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-ant (1.0 MB)
  { id: "5zltoZznV2UePzpOwh", who: "Timberwolves" },  // nba-minnesota-timberwolves (1.1 MB)
  { id: "jxEEiQpGWQ4ZvmNECk", who: "Rudy Gobert" },  // timberwolves-nba-minnesota-rudy (1.1 MB)
  { id: "PkeETwtsKUM2LgqIj3", who: "Naz Reid" },  // timberwolves-nba-minnesota-nazreid (1.2 MB)
  { id: "Gq96sJdst20QYqkYA6", who: "Anthony Edwards" },  // nba-anthony-edwards (1.3 MB)
  { id: "4pfl3wtSNVdMjUe1MA", who: "Anthony Edwards" },  // nba-ant-antman-anthonyedwards (1.3 MB)
  { id: "o84yrDXMBzHN0lPGpB", who: "Julius Randle" },  // nba-nba-playoffs-julius-randle-2025 (1.3 MB)
  { id: "1CIGKTnZbinYZ8TLjx", who: "Anthony Edwards" },  // nba-timberwolves-anthony-edwards-game-7 (1.4 MB)
  { id: "OIiKYamsmHPMEZY70Z", who: "Rudy Gobert" },  // timberwolves-minnesota-rudy-rudygobert (1.4 MB)
  { id: "f93t6mS35iSpbql6dV", who: "Jaden McDaniels" },  // timberwolves-nba-minnesota-jadenmcdaniels (1.5 MB)
  { id: "BrH6IE1ti3l5CaEMxz", who: "Nickeil Alexander-Walker" },  // timberwolves-three-nickeil-alexander-walker (1.8 MB)
  { id: "l0ErWPD084DkwIDiE", who: "Timberwolves" },  // nba-basketball-minnesota-timberwolves (1.8 MB)
  { id: "sEKQerIfi4LFqNQQgt", who: "Rudy Gobert" },  // timberwolves-nba-minnesota-rudygobert (1.8 MB)
  { id: "8z8O0Q3PvrAcOKb0Bv", who: "Timberwolves" },  // timberwolves-nba-hype-minnesota (1.8 MB)
  { id: "gZTBdpYk4wNvvKLL37", who: "Anthony Edwards" },  // nba-staring-timberwolves-ant-edwards (1.8 MB)
  { id: "g0rcec4Z3iy5BIssVW", who: "Anthony Edwards" },  // nba-nba-regular-season-anthony-edwards-ant (1.9 MB)
  { id: "X7giy8Q3d2XP4ACqnJ", who: "Timberwolves" },  // timberwolves (2.0 MB)
  { id: "uEv6jZFB1TL3YeQy5f", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-ant (2.0 MB)
  { id: "tm82RgyjwTVlZPlBSv", who: "Naz Reid" },  // timberwolves-nba-minnesota-nazreid (2.1 MB)
  { id: "1KQCOgSECSQOfOYeQE", who: "Naz Reid" },  // timberwolves-nba-minnesota-naz (2.1 MB)
  { id: "v04lQGhtQEGQnpowc8", who: "Julius Randle" },  // timberwolves-nba-minnesota-juliusrandle (2.1 MB)
  { id: "p20pHEnAZjGYTcGCDf", who: "Anthony Edwards" },  // timberwolves-minnesota-ant-anthonyedwards (2.1 MB)
  { id: "7DcyhJ92duUuFP98w4", who: "Naz Reid" },  // timberwolves-reid-naz-nazreid (2.1 MB)
  { id: "71R4orL2VY4LDqvoon", who: "Anthony Edwards" },  // nba-nba-playoffs-anthony-edwards-2025 (2.2 MB)
  { id: "MadVnyBPqZ1eILuVyK", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-ant (2.2 MB)
  { id: "3bTxD1roiDiCc1UTqA", who: "Anthony Edwards" },  // timberwolves-nba-fans-ant (2.3 MB)
  { id: "hAbCmNm8cSvvsbDLCV", who: "Timberwolves" },  // timberwolves-nba-minnesota-raisetheroof (2.4 MB)
  { id: "JeHuEUL2gzFkC0dgBk", who: "Timberwolves" },  // timberwolves-nba-minnesota-wolves (2.4 MB)
  { id: "eeG8nx7H5GesEJYQGL", who: "Jaden McDaniels" },  // timberwolves-nba-minnesota-jadenmcdaniels (2.4 MB)
  { id: "h8BxgnBmhtvGm0n5zr", who: "Rob Dillingham" },  // timberwolves-nba-minnesota-robdillingham (2.5 MB)
  { id: "zgRb80n8bB8I1V82UJ", who: "Timberwolves" },  // timberwolves (2.6 MB)
  { id: "AlVEKzoKM9qyKrQogK", who: "Naz Reid" },  // timberwolves-nba-minnesota-nazreid (2.7 MB)
  { id: "Il9CGAWB0QmRvffLQ9", who: "Anthony Edwards" },  // timberwolves-minnesota-ant-anthonyedwards (2.8 MB)
  { id: "iut31gfam0gzAEk8Fy", who: "Julius Randle" },  // timberwolves-nba-minnesota-juliusrandle (2.9 MB)
  { id: "0t91WKkCTA5lA71wEK", who: "Julius Randle" },  // nba-ant-man-julius-randle-edwards (2.9 MB)
  { id: "8JiGo1dhUALtqBRLpP", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-anthonyedwards (2.9 MB)
  { id: "yjJCnzmf6XfsIhwPz8", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-ant (3.0 MB)
  { id: "arn9lbwz66wQwyTyDR", who: "Naz Reid" },  // timberwolves-nba-minnesota-nazreid (3.0 MB)
  { id: "bqbXv50llMsWklsR1y", who: "Anthony Edwards" },  // nba-ant-antman-anthonyedwards (3.0 MB)
  { id: "kK4YnYxpOqN3StJ6Gn", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-anthonyedwards (3.0 MB)
  { id: "GfMqHZB7xuYv9HfkqP", who: "Naz Reid" },  // timberwolves-reid-naz-nazreid (3.1 MB)
  { id: "8XXWaanElJjMf0uAVj", who: "Anthony Edwards" },  // nba-ant-man-timberwolves-anthony-edwards (3.3 MB)
  { id: "7NB3aTtdW6vUIidpQv", who: "Anthony Edwards" },  // nba-ant-antman-anthonyedwards (3.3 MB)
  { id: "1BLb96wGXTs5p9YCiy", who: "Anthony Edwards" },  // nba-nba-regular-season-ant-man-edwards (3.3 MB)
  { id: "O0YEl2eFyEVx6oTSN7", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-ant (3.3 MB)
  { id: "MMckNS02RjTwc8lujr", who: "Julius Randle" },  // nba-minnesota-timberwolves-julius-randle (3.4 MB)
  { id: "EHnjZ1VmcFnO9l0xcf", who: "Naz Reid" },  // timberwolves-nba-minnesota-nazreid (3.4 MB)
  { id: "HFpuvC5RH9jnkV8r4C", who: "Anthony Edwards" },  // nba-dunk-ant-edwards (3.4 MB)
  { id: "sDZMUkGlWhAlBIs8dZ", who: "Anthony Edwards" },  // anthony-edwards-mylesthe1-dunk (3.5 MB)
  { id: "14B9glqE0BqOp6t8FO", who: "Anthony Edwards" },  // nba-reaction-ant-man-ant-edwards (3.5 MB)
  { id: "nat8H6FVqJ43xLdPw0", who: "Naz Reid" },  // timberwolves-reid-naz-nazreid (3.6 MB)
  { id: "xAkY0mWhn9IYrhyJqd", who: "Anthony Edwards" },  // nba-anthony-edwards-poster-dunk-one-handed (3.7 MB)
  { id: "FB2PuhFX3iKE8pC5eE", who: "Anthony Edwards" },  // nba-ant-man-timberwolves-anthony-edwards (3.8 MB)
  { id: "sMCxwTZxJUwjAaGZRm", who: "Anthony Edwards" },  // timberwolves-nba-minnesota-ant (3.8 MB)
  { id: "tgFoSLPAfxHclz6Qfo", who: "Anthony Edwards" },  // nba-minnesota-timberwolves-ant-edwards (3.9 MB)
  { id: "mMxpFeQfUBImQLy6si", who: "Naz Reid" },  // timberwolves-dunk-naz-reid (3.9 MB)
  { id: "1MXwCgVw85unpwFPvC", who: "Anthony Edwards" },  // timberwolves-antman-anthonyedwards-antedwards (4.0 MB)
  { id: "OpOcEaY7FQLOD6kinI", who: "Timberwolves" },  // timberwolves-nba-minnesota-wolves (4.1 MB)
  { id: "d7b0h49nm4VZVDkz77", who: "Anthony Edwards" },  // nba-minnesota-timberwolves-ant-edwards (4.4 MB)
  { id: "lfGWHMgcauqNjhh0VH", who: "Timberwolves" },  // timberwolves-smile-dap-highfives (4.5 MB)
  { id: "hTjzetNUv8La6OBm0D", who: "Timberwolves" },  // nba-nba-regular-season-minnesota-timberwolves (4.5 MB)
];
